export declare class WizardFunctions {
    private currentQuestionIndex;
    private questionsApiRetryCount;
    private questions;
    private questionsApiQueryParams;
    private defaultTopPosition;
    private defaultRightPosition;
    private defaultLeftPosition;
    private dynamicsQuestionApi;
    private questionQueryList;
    private questionList;
    private tracking;
    constructor();
    private fetchNewQuestion;
    private fetchFirstQuestion;
    private getWizardContent;
    private initializeWizard;
    private addQuestionAnswerHtml;
    private initializeFirstQuestion;
    private isPniWizardOpen;
    private triggerTrackingEvent;
    private handleOptionChange;
    private wizardPositioning;
    private reevaluateQuestions;
    private setQuestionsQuery;
    private setNewQuestion;
    private addResetButton;
    private positioningAndTracking;
    private populateWizard;
    private removeRepetitiveElements;
    openInteractiveWizard: () => void;
    private showHideResetButton;
    showNextQuestion(questionSequence: number, answerValue: string): Promise<void>;
    private resetWizard;
    clearAllQuestions: () => void;
    closeInteractiveWizard: () => void;
}
